monolog:
    handlers:
        main:
            type: fingers_crossed
            handler: syslog_handler
            excluded_http_codes:
                - {400: ['^/api/']}
                - {401: ['^/api/']}
                - 403
                - 404
                - {405: ['/homepage$', '/login_check$', '/export/data$']}
            channels: ["!deprecation"]
        syslog_handler:
            type: syslog
            ident: kimai
            level: info
        console:
            type: console
            process_psr_3_messages: false
            level: info
